# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty

timezone: America/Chicago

# Exclude metadata and development time dependencies (like node modules)
exclude: [README.md, node_modules]
include: [assets]
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]